spring:
  application:
    name: auth-service-prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  port: 8080
  forward-headers-strategy: framework
  shutdown: graceful

jwt:
  secret-string: ${SECRET_STRING}

cors:
  allowed-origins:
    - "https://koreaevent.click"
    - "https://www.koreaevent.click"

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /auth/actuator
      exposure:
        include: health, prometheus
#  metrics:
#    tags:
#      application: ${spring.application.name}
#      pod: ${HOSTNAME:unknown}