apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: event
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: event
data:
  SPRING_APPLICATION_NAME: "auth-service"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://event-database.cxgqgiu6orpo.ap-northeast-2.rds.amazonaws.com:5432/auth_db"