apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: event
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: event
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "authu"
  SPRING_DATASOURCE_PASSWORD: "authp"
  SECRET_STRING: "QUhvbWVSdW5IaXREb3VibGVUcmlwbGVUaGVHcmFuZFNsYW0" # AHomeRunHitDoubleTripleTheGrandSlam를 base64로 인코딩한 값