services:
  event-postgres-service:
    image: postgres:16
    container_name: event-postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"
    networks:
      - event_network
    volumes:
      - /Users/styner/0main/docker-volumes/event-core/postgresql/data:/var/lib/postgresql/data

networks:
  event_network:
    driver: bridge