apiVersion: v1
kind: ConfigMap
metadata:
  name: event-core-config
  namespace: event
  labels:
    app.kubernetes.io/name: event-core
    app.kubernetes.io/part-of: event
data:
  SPRING_APPLICATION_NAME: "event-core"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://event-database.cxgqgiu6orpo.ap-northeast-2.rds.amazonaws.com:5432/event_db"
  TZ: "UTC"
  JAVA_TOOL_OPTIONS: "-Duser.timezone=UTC"
  SPRING_JACKSON_TIME_ZONE: "UTC"