apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-core-deployment
  namespace: event
  labels:
    app.kubernetes.io/name: event-core
    app.kubernetes.io/part-of: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: event-core
  template:
    metadata:
      labels:
        app.kubernetes.io/name: event-core
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: event-core
        image: 235704034905.dkr.ecr.ap-northeast-2.amazonaws.com/event-core:0.0.10
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
        envFrom:
        - configMapRef:
            name: event-core-config
        - secretRef:
            name: event-core-secret
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /events/actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          failureThreshold: 3
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /events/actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0