spring:
  application:
    name: bridge-service-prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  devtools:
    add-properties: false
  kafka:
    bootstrap-servers: my-kafka.kafka.svc.cluster.local:9092

server:
  port: 8080
  forward-headers-strategy: framework
  shutdown: graceful

public-data-api:
  service-key: ${SERVICE_KEY}

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus