services:
  auth-postgres-service:
    image: postgres:16
    container_name: auth-postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
    command: ["postgres", "-c", "TimeZone=UTC"]
    ports:
      - "35432:5432"
    networks:
      - msa_network
    volumes:
      - /Users/styner/0main/docker-volumes/auth-service/postgresql/data:/var/lib/postgresql/data
  auth-redis-service:
    image: redis:7.0-alpine
    container_name: auth-redis-container
    ports:
      - "36379:6379"
    networks:
      - msa_network
    volumes:
      - /Users/styner/0main/docker-volumes/auth-service/redis/data:/data
    command: redis-server --appendonly yes # Redis가 AOF 모드로 동작

networks:
  msa_network:
    external: true