services:

  bridge-zookeeper-service:
    image: confluentinc/cp-zookeeper:latest
    container_name: bridge-zookeeper-container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - bridge_network
    volumes:
      - /Users/styner/0main/docker-volumes/bridge-service/zookeeper/data:/data
      - /Users/styner/0main/docker-volumes/bridge-service/zookeeper/datalog:/datalog

  bridge-kafka-service:
    image: confluentinc/cp-kafka:latest
    container_name: bridge-kafka-container
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: bridge-zookeeper-service:2181
      #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - bridge-zookeeper-service
    networks:
      - bridge_network
    volumes:
      - /Users/styner/0main/docker-volumes/bridge-service/kafka/data:/var/lib/kafka/data

  bridge-postgres-service:
    image: postgres:16
    container_name: bridge-postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
    command: ["postgres", "-c", "TimeZone=UTC"]
    ports:
      - "25432:5432"
    networks:
      - bridge_network
    volumes:
      - /Users/styner/0main/docker-volumes/bridge-service/postgresql/data:/var/lib/postgresql/data

networks:
  bridge_network:
    driver: bridge
