apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-ingress
  namespace: event
  labels:
    app.kubernetes.io/name: event-ingress
    app.kubernetes.io/part-of: event
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:235704034905:certificate/c0d98f0a-da5a-4266-b315-e1adb282b325
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
    - host: "api.koreaevent.click"
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service-service
                port:
                  number: 8080
          - path: /events
            pathType: Prefix
            backend:
              service:
                name: event-core-service
                port:
                  number: 8080
          - path: /ai
            pathType: Prefix
            backend:
              service:
                name: event-core-service
                port:
                  number: 8080